### ISSUE TITLE
ERROR: Unable to reach the SpliceAI-lookup API server. Either the API server is down or your internet isn't working.

### ISSUE THREAD

**Issue by redmoon6584** [broadinstitute/SpliceAI-lookup#12] opened 2021-07-23 13:47 UTC
Hello,

When I try to run SpliceAI (https://spliceailookup.broadinstitute.org/), I get the following error message:
ERROR: Unable to reach the SpliceAI-lookup API server. Either the API server is down or your internet isn't working.

I have no issues with my internet, so I thought I would report this in case there is wrong with something in the API server.

Thank you!

**Comment by WhispAllium** [comment] 2021-07-23 15:21
Same here. The main page hasn't been working, and the API links haven't been working, for about a day or two.

**Comment by bw2** [comment] 2021-07-23 16:51
Apologies, and thanks for letting me know. I'm restarting the server now. 
It appears there were intermittent outages that did not trigger alerts. I'm looking into the issue.

**Comment by bw2** [comment] 2021-07-23 17:18
It's an SSL certificate issue with the api server. This might take some time to update.

**Comment by bw2** [comment] 2021-07-23 21:43
This is fixed now. Please let me know if you continue to experience an issue
even after a full refresh of the page (Command-R on Mac, or Ctrl-R on windows).

**Comment by bw2** [comment] 2021-07-23 21:53
I spoke too soon - it needs another 10 minutes to reboot one more time.

**Comment by bw2** [comment] 2021-07-23 22:19
ok, now it's working again.

**Closed by bw2** 2021-07-23 22:19 UTC

**Comment by redmoon6584** [comment] 2021-07-23 22:31
Thank you!

**Comment by beboche** [comment] 2021-07-30 08:07
Hi,

I have a related issue. I'am accessing the API using a python script, urllib3 certifi, and the new certificate fails to validate. I have the error:

`urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='spliceailookup-api.broadinstitute.org', port=443): Max retries exceeded with url: /spliceai/?hg=38&distance=500&mask=1&variant=chr21-42375852-G-A (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:877)'),))`

Are you aware of it? I would like to avoid disabling certificate validation.
Thanks!

**Comment by bw2** [comment] 2021-07-30 13:07
Hmm.. I'm not able to reproduce this. 
For example I can go to  
https://spliceailookup-api.broadinstitute.org/spliceai/?hg=38&distance=50&mask=0&precomputed=0&variant=8-140300616-T-G&raw=chr8-140300616-T-G
in Chrome, and it has no issue with the certificate:
![image](https://user-images.githubusercontent.com/6240170/127657212-d3ab36f6-51d3-4a69-ace2-6de034fb2733.png)

Then, if I click on "Certificate" it shows
![image](https://user-images.githubusercontent.com/6240170/127657244-df8e9a5d-7857-4281-8c73-f312d3acb30e.png)

**Comment by beboche** [comment] 2021-07-30 13:12
yes using a web browser it works well, that's what is strange. But the python script still refuses to connect.
Thanks for answering, I'll do some research from my side.
